name: Create PR

on:
  issues:
    types: [edited, labeled, unlabeled]
  issue_comment:
    types: [created, edited, deleted]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    name: Create PR
    if: "!contains(github.event.comment.body , '[vx.dev]') && !contains(github.event.comment.body , '[Dewhale]') && github.event.comment.user.type != 'bot'"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.38.3
      - name: generate UI
        env:
          GH_TOKEN: "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"
          OPENAI_API_KEY: "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"
          WHITELIST: "zhanglingsi1"
          CONFIG: ${{ vars.CONFIG }}
          ACTOR: ${{ github.actor }}
        run: deno run -A prompts/entry.ts
